### ISSUE TITLE
Error running demo without nightly

### ISSUE THREAD

**Issue by adamkrawczyk** [openrr/rrt#14]
Hi, 

I got the following error running the demo - also I don't want to switch to nightly. 

```
error: failed to parse manifest at `/home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/nalgebra-0.26.2/Cargo.toml`

Caused by:
  feature `resolver` is required

  this Cargo does not support nightly features, but if you
  switch to nightly channel you can add
  `cargo-features = ["resolver"]` to enable this feature
```

Best

**Comment by taiki-e** [comment]
Seems you are using the old compiler. You have to use Rust 1.51+.

**Comment by adamkrawczyk** [comment]
Thank you, I was using `rustc 1.50.0 (cb75ad5db 2021-02-10)` after switching to `rustc 1.52.0 (88f19c6da 2021-05-03)` works!

Sorry for false alarm :)
